Promos:
    type: entity
    table: promos
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        number:
            type: string
            nullable: true
            length: 9
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
