Publicholidays:
    type: entity
    table: publicholidays
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: true
            comment: ''
    lifecycleCallbacks: {  }
