<?php

namespace Planning\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstablishmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablishmentsRepository extends EntityRepository
{
    
}
