<?php

namespace Planning\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HolidaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidaysRepository extends EntityRepository
{
}
