<?php

namespace Planning\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningsRepository extends EntityRepository
{
}
